"""
черный список приложений - имена
"""

check_list_names = [
    "GetApps",
    "Mi Store",
    "Poco Store",
    "Mi Credit",
    "MiPay",
    "MiPay",
    "MiPay Service",
    "Joyose",
    "Mi Community",
    "Poco Community",
    "Mi Coin",
    "ShareMe",
    "MSA Xiaomi",
    "Quick Apps",
    "Quick Apps Accessory",
    "Soter Service",
    "Yellow Pages",
    "Mi Wallpaper Carousel",
    "Mi Analytics",
    "Mi Bugreport",
    "Xiaomi Services & Feedback",
    "Digital Wellbeing",
    "Emoji Keyboard",
    "Emoji Keyboard Global Rom",
    "Mi Remote",
    "Facebook",
    "Facebook App Manager",
    "Facebook App Installer",
    "Facebook Services",
    "Amazon Shopping",
    "LinkedIn",
    "Spotify",
    "Netflix",
    "AliExpress",
    "eBay",
    "eBay Carrier",
    "WPS Office",
    "Yandex Search Plugin",
    "Yandex ZEN",
    "Yandex ZEN Partnerconfig",
    "Yandex Satellite",
    "Yandex Browser",
    "Yandex Market",
    "TikTok",
    "Opera",
    "Opera Preinstall",
    "Booking",
    "Kaspersky Internet Security",
    "ivi",
    "2GIS",
    "BIGO LIVE",
    "Tile Fun",
    "Dust Settle",
    "Lords Mobile",
    "Bubble Shooter Relaxing",
    "Funmax",
    "Tinkoff",
    "Device Health Services",
    "Google",
    "Google Play Newsstand",
    "Google Podcasts",
    "Google TV",
    "Google Photos",
    "YouTube",
    "YouTube Music",
    "Google Docs",
    "Google Maps",
    "Google Location History",
    "Google One",
    "Google Meet",
    "GPay",
    "Google Chrome",
    "Gmail",
    "Google Assistant",
    "X Google Enrollment",
    "OK Google Enrollment",
    "Speech Services by Google",
    "Gboard",
    "Android Auto",
    "Google Partner Setup",
    "Market Feedback Agent",
    "Partner Bookmarks",
    "Bookmark Povider",
    "Emergency Location Service (ELS)",
    "Cell Broadcast",
    "Cell Broadcast",
    "Cell Broadcast Service",
    "Cell Broadcast Receiver Overlay",
    "Cell Broadcast Receiver Overlay",
    "Cell Broadcast Service Overlay",
    "Photo Screensavers",
    "Basic Daydreams",
    "Live Wallpaper Picker",
    "Wallpaper Backup",
    "Wallpaper Cropper",
    "BuiltInPrintService",
    "Print Service Recommendation Service",
    "Print Spooler",
    "SIM Toolkit App",
    "Smart-Divert",
    "Qualcomm eMBMS",
    "Android Easter Egg",
    "Google One Time Init",
]
